DROP TABLE IF EXISTS entries;
CREATE TABLE entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  text TEXT NOT NULL,
  image TEXT NOT NULL,
  music TEXT NOT NULL,
  posted TIMESTAMP NOT NULL
);
